applications: nrf5340_audio: Remove all references to BT_LL_ACS_NRF53
koffes/sdk-nrf pull request #5
Opened 2024-04-04 10:11 UTC by alexsven

- Only the Nordic SoftDevice is supported
- OCT-2908

2024-04-04 14:17 UTC, koffes requested changes

2024-04-04 14:17 UTC, koffes commented on applications/nrf5340_audio/LICENSE
We need to discuss this one as there are still PCFT elements left.

2024-04-04 14:17 UTC, koffes commented on lib/bin/bt_ll_acs_nrf53/CMakeLists.txt
In my PR I deleted the entire folder. We can keep this as is and I can rebase.

2024-04-05 08:58 UTC, alexsven commented on applications/nrf5340_audio/LICENSE
It's now back

2024-04-05 09:51 UTC, merged